rest_dealing_list:
    path:     /dealing/from/{from}/to/{to}
    defaults: { _controller: MyRestBundle:Default:dealingList }
    requirements:
        from: \d{8}$
        to: \d{8}$

rest_dealing_regist:
    path:     /dealing/regist
    defaults: { _controller: MyRestBundle:Default:dealingRegist }
    
rest_dealing_show:
    path:     /dealing/{id}
    defaults: { _controller: MyRestBundle:Default:dealingShow }
    
rest_dealing_type_list:
    path:     /dealing_type
    defaults: { _controller: MyRestBundle:Default:dealingTypeList }

rest_test:
    path:     /test
    defaults: { _controller: MyRestBundle:Default:index }
    

    
