CREATE DATABASE finance DEFAULT CHARACTER SET 'utf8';

CREATE USER 'finance'@'localhost' IDENTIFIED BY 'finance';
GRANT USAGE ON *.* TO 'finance'@'localhost' IDENTIFIED BY 'finance' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON `finance`.* TO 'finance'@'localhost'WITH GRANT OPTION;
